import type { Metadata } from "next";
import { DM_Sans, Fraunces, DM_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: ['400', '500',],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Masion Soleil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${dmMono.variable} ${dmSans.variable}`}
    >
      <body>
        <Navbar />
        <main className="py-8 min-h-screen lg:ml-65 space-y-10">
          {children}
        </main>
        </body>
    </html>
  );
}
